### ISSUE TITLE
Team stats not working unless `packs` is configured correctly

### ISSUE THREAD

**Issue by iMacTia** [rubyatscale/pack_stats#29]
This gem rightly supports additional paths for packages on top of the default `/packs`.
However, while searching for team ownership, the gem will completely rely on the `packs` gem, which by default DOES NOT check any other path.

Since at my org we use a different root folder for our packages, I realised all our metrics were being tagged with `team:Unknown`.
To fix that, I had to add a `packs.yml` config file to our app, but I was only able to figure that out after digging through the code of multiple gems.

If this is indeed the way to go, should we point this out in the README to save people time in future?
Even better, could this gem or `packs` somehow be smart enough to figure that out based on some other config (e.g. `stimpack`)?

**Comment by alexevanczuk** [comment]
@iMacTia Thank you for filing this issue. You're right -- this was pretty unclear. I've pushed a commit to add a note at the top of the README on configuring `packs`. Let me know if this helps or if we can make any tweaks to it.

> Even better, could this gem or packs somehow be smart enough to figure that out based on some other config (e.g. stimpack)?

Now that `stimpack` has been rebranded to `packs-rails`, my hope is that this API should be a bit more stable and shouldn't need to look for other sources of truth for the time being 🙏

**Comment by iMacTia** [comment]
Hey @alexevanczuk, yes that helps for sure 🙏 !
Glad to see all these gems slowly moving to more stable APIs, exciting to see them all work together!

**Comment by alexevanczuk** [comment]
Perfect, thanks @iMacTia. Thanks for the kind words and your patience in the process 🙏
