### ISSUE TITLE
CodeTeams dependency feels onerous

### ISSUE THREAD

**Issue by timjnh** [rubyatscale/pack_stats#45]
Just a bit of feedback, the indirect dependency on CodeTeams and its requirement that all teams be defined in separate files in config/teams feels a bit onerous in order to get metrics by team.  I was hoping I could just add `owner` attributes to my package.yml files.  Having the additional dependency/step makes it a harder sell to my org.  It's minor, I know, but when you're trying to make a big step like adopting packwerk every little friction point and quirk adds up.

I dug around a bit in the code and couldn't see a super obvious way to make this happen.  Maybe `PackageOwnership.owner_for_package` could catch a more specific error type from CodeTeam and optionally just use the team name from the package config.

**Comment by professor** [comment]
Thank you for your feedback. We agree that it would be ideal that if you want metrics for one team, you'd only need to have one team in `config/teams` 

Our suggestion would be to put in minimal amount of information for all your teams.
