### ISSUE TITLE
Include an example of the dashboard in the README

### ISSUE THREAD

**Issue by Catsuko** [rubyatscale/pack_stats#49]
I am interested in this gem however I would love to know more about:
>This gem is used to report opinionated statistics about modularization

Rather than needing to dive into the dashboard json, I would like to see an image showing the dashboard for a sample project so that I could get a better idea of what these opinionated statistics are.

**Comment by tstannard** [comment]
Hi @Catsuko, 

I don't have a dashboard of a sample project but I can give you the titles of the graphs we use in ours: 
- Violations by package 
- Violations by team
- Packwerk usage by teams (which packs enforce different violation types)
- Overall violations 
- % of packs with non empty API's 
- Packs most depended on

**Comment by Catsuko** [comment]
hello @tstannard

Are those graphs provided by this gem or something your team has put together? Mainly I want to know if I add this gem and add the dashboard, what do I get? 🤔

**Comment by tstannard** [comment]
Hi @Catsuko 

Is [this](https://github.com/rubyatscale/pack_stats/blob/main/docs/screenshots.md) what you are looking for?

**Comment by Catsuko** [comment]
yes, thank you for the update 🙏
